import { AgentConfig } from '@/types';

export const PROJECT = {
  name: '상주시 시니어복합센터 건립사업',
  location: '경북 상주시 무양동 11-1번지 외 4필지',
  client: '상주시',
  floorArea: '연면적 2,200㎡',
  floors: '지하1층+지상4층',
  budget: '98억원',
  deadline: '2026년 6월 2일',
  purpose: '시니어 복합 커뮤니티 시설',
  region: '경상북도 상주시',
  submitDate: '2026-06-02',
} as const;

export const AGENT_CONFIGS: AgentConfig[] = [
  {
    key: 'guidelines',
    title: '지침분석',
    subtitle: '체크리스트 49항목',
    icon: '📋',
    colorClass: 'text-blue-400',
    borderClass: 'border-blue-500/40',
    bgClass: 'bg-blue-500/10',
  },
  {
    key: 'siteAnalysis',
    title: '대지분석',
    subtitle: 'SWOT·주변환경 분석',
    icon: '🗺️',
    colorClass: 'text-emerald-400',
    borderClass: 'border-emerald-500/40',
    bgClass: 'bg-emerald-500/10',
  },
  {
    key: 'report',
    title: '보고서 생성',
    subtitle: '8섹션 자동 생성',
    icon: '📊',
    colorClass: 'text-purple-400',
    borderClass: 'border-purple-500/40',
    bgClass: 'bg-purple-500/10',
  },
  {
    key: 'concept',
    title: '컨셉 제안',
    subtitle: '설계 컨셉 + 점수 예측',
    icon: '💡',
    colorClass: 'text-yellow-400',
    borderClass: 'border-yellow-500/40',
    bgClass: 'bg-yellow-500/10',
  },
  {
    key: 'description',
    title: '설계설명서',
    subtitle: '10섹션 자동 작성',
    icon: '📝',
    colorClass: 'text-orange-400',
    borderClass: 'border-orange-500/40',
    bgClass: 'bg-orange-500/10',
  },
  {
    key: 'layoutPlan',
    title: '배치·평면계획',
    subtitle: '3가지 배치대안',
    icon: '📐',
    colorClass: 'text-cyan-400',
    borderClass: 'border-cyan-500/40',
    bgClass: 'bg-cyan-500/10',
  },
  {
    key: 'exterior',
    title: '외관디자인',
    subtitle: 'SVG 입면도 + 재료',
    icon: '🏛️',
    colorClass: 'text-rose-400',
    borderClass: 'border-rose-500/40',
    bgClass: 'bg-rose-500/10',
  },
  {
    key: 'massDesign',
    title: '매스디자인',
    subtitle: '아이소메트릭 3D',
    icon: '🧊',
    colorClass: 'text-indigo-400',
    borderClass: 'border-indigo-500/40',
    bgClass: 'bg-indigo-500/10',
  },
];
